version: '3.8'

services:
  app:
#    build:
    image: ghcr.io/chatgut/urlshortenerservice2:main
    container_name: RobertService

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db:
  dbAuth:
  dbData:
  db_mysql: